USE PP_DDBB;
GO

CREATE OR ALTER PROCEDURE sp_wdev_user_create_user_connection
    @USERNAME NVARCHAR(25),
    @CONNECTION_ID UNIQUEIDENTIFIER,
    @ret INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO USER_CONNECTIONS
        (CONNECTION_ID, USER_ID, USERNAME, DATE_CONNECTED)
    VALUES
        (@CONNECTION_ID, (SELECT ID FROM USERS WHERE USERNAME = @USERNAME), @USERNAME, CONVERT(DATETIME, SWITCHOFFSET(SYSDATETIMEOFFSET(), '+02:00')));

    UPDATE USERS SET LOGIN_STATUS = 1 WHERE USERNAME = @USERNAME;

    IF @@ROWCOUNT = 1
    BEGIN
        SET @ret = 0;
    END
    ELSE
    BEGIN
        SET @ret = -1; -- Algo salió mal durante la creación de la conexión
    END
END;
GO
