USE PP_DDBB;

-- fn_mail_exists
go
CREATE OR ALTER FUNCTION fn_mail_exists (@EMAIL NVARCHAR(100))
RETURNS BIT
AS
BEGIN
    DECLARE @Exists BIT;
    SET @Exists = (
        SELECT CASE WHEN EXISTS (SELECT 1 FROM USERS WHERE EMAIL = @EMAIL) THEN 1 ELSE 0 END
    );
    RETURN @Exists;
END;
GO