
USE PP_DDBB;

----- TABLES -----

CREATE TABLE STATUS(
    STATUS INT PRIMARY KEY,
    DESCRIPTION VARCHAR (25)
);
GO
CREATE TABLE USERS(
    ID INT PRIMARY KEY IDENTITY(1,1),
    USERNAME NVARCHAR(25) UNIQUE,
    NAME NVARCHAR(25),
    LASTNAME NVARCHAR(50),
    PASSWORD NVARCHAR(50),
    EMAIL NVARCHAR(100),
    STATUS INT FOREIGN KEY REFERENCES STATUS(STATUS),
    GENDER BIT,
    DEF_LANG NVARCHAR(3),
    TIMESTAMP DATETIME DEFAULT CONVERT(DATETIME, SWITCHOFFSET(SYSDATETIMEOFFSET(), '+02:00')), -- Ajustar al desplazamiento horario de tu zona
    REGISTER_CODE INT,
    LOGIN_STATUS BIT,
    ROL_USER BIT
);
go
CREATE TABLE PWD_HISTORY(
    HISTORY_ID INT PRIMARY KEY IDENTITY(1,1),
    USER_ID INT,
    USERNAME NVARCHAR(25),
    OLD_PASSWORD NVARCHAR(50),
    DATE_CHANGED DATETIME DEFAULT CONVERT(DATETIME, SWITCHOFFSET(SYSDATETIMEOFFSET(), '+02:00')), -- Ajustar al desplazamiento horario de tu zona
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
go
CREATE TABLE USER_CONNECTIONS(
    CONNECTION_ID UNIQUEIDENTIFIER PRIMARY KEY,
    USER_ID INT,
    USERNAME NVARCHAR(25),
    DATE_CONNECTED DATETIME DEFAULT CONVERT(DATETIME, SWITCHOFFSET(SYSDATETIMEOFFSET(), '+02:00')), -- Ajustar al desplazamiento horario de tu zona
    DATE_DISCONNECTED DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
go
CREATE TABLE USER_CONNECTIONS_HISTORY(
    HISTORY_ID INT PRIMARY KEY IDENTITY(1,1),
    USER_ID INT,
    USERNAME NVARCHAR(30),
    DATE_CONNECTED DATETIME DEFAULT CONVERT(DATETIME, SWITCHOFFSET(SYSDATETIMEOFFSET(), '+02:00')),
    DATE_DISCONNECTED DATETIME DEFAULT CONVERT(DATETIME, SWITCHOFFSET(SYSDATETIMEOFFSET(), '+02:00')),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

go

-- Crear la tabla de errores
CREATE TABLE USER_ERRORS (
    ERROR_ID INT PRIMARY KEY IDENTITY(0,1),
    ERROR_CODE INT NOT NULL,
    ERROR_MESSAGE NVARCHAR(MAX) NOT NULL,
);
