USE PP_DDBB;

----- TABLES -----

CREATE TABLE STATUS(
    STATUS INT PRIMARY KEY,
    DESCRIPTION VARCHAR (25)
);

CREATE TABLE USERS(
    ID INT PRIMARY KEY IDENTITY(1,1),
    USERNAME NVARCHAR(25) UNIQUE,
    NAME NVARCHAR(25),
    LASTNAME NVARCHAR(50),
    PASSWORD NVARCHAR(50),
    EMAIL NVARCHAR(30) UNIQUE,
    STATUS INT FOREIGN KEY REFERENCES STATUS(STATUS),
    GENDER CHAR(1),
    DEF_LANG NVARCHAR(3),
    TIMESTAMP DATETIME DEFAULT GETDATE(),
    REGISTER_CODE INT
);

CREATE TABLE PWD_HISTORY(
    HISTORY_ID INT PRIMARY KEY IDENTITY(1,1),
    USER_ID INT,
    OLD_PASSWORD NVARCHAR(50),
    DATE_CHANGED DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE USER_CONNECTIONS(
    CONNECTION_ID UNIQUEIDENTIFIER PRIMARY KEY,
    USER_ID INT,
    DATE_CONNECTED DATETIME DEFAULT GETDATE(),
    DATE_DISCONNECTED DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE USER_CONNECTIONS_HISTORY(
    HISTORY_ID INT PRIMARY KEY IDENTITY(1,1),
    USER_ID INT,
    USERNAME NVARCHAR(30),
    DATE_CONNECTED DATETIME,
    DATE_DISCONNECTED DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);


-- -- Crear la tabla de errores
-- CREATE TABLE USER_ERRORS (
--     ERROR_ID INT PRIMARY KEY IDENTITY(0,1),
--     ERROR_CODE NVARCHAR(50) NOT NULL,
--     ERROR_MESSAGE NVARCHAR(MAX) NOT NULL,
--     ERROR_TIMESTAMP DATETIME DEFAULT GETDATE()
-- );
