USE PP_DDBB;

-- DELETE FROM USERS WHERE id=12;
-- DELETE FROM USERS WHERE USERNAME='sample_user';

DELETE FROM USERS;
DELETE FROM PWD_HISTORY;
DELETE FROM USER_CONNECTIONS;
DELETE FROM USER_CONNECTIONS_HISTORY;
DELETE FROM USER_ERRORS;