USE PP_DDBB;
----- DROPS -----

DROP TABLE IF EXISTS STATUS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PWD_HISTORY;
DROP TABLE IF EXISTS USER_CONNECTIONS;
DROP TABLE IF EXISTS USER_CONNECTIONS_HISTORY;
DROP TABLE IF EXISTS USER_ERRORS;
GO