USE PP_DDBB;

----- SELECTS -----
SELECT * FROM STATUS;
SELECT * FROM USERS;
SELECT * FROM USER_CONNECTIONS;
SELECT * FROM USER_CONNECTIONS_HISTORY;
SELECT * FROM PWD_HISTORY;
SELECT * FROM USER_ERRORS;